# Site settings
title: ILLSA
subtitle: International Language and Linguistics Students' Association
email: presidency.illsa@gmail.com
description: International Language and Linguistics Students' Association
baseurl: "/" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
author:
street_address: 
city: 
state: 
zip_code: 
country: 
phone: 

# Social settings
500px_url:
facebook_url: https://www.facebook.com/illsaorg
github_url:
gitlab_url: 
googleplus_url: 
instagram_url: 
linkedin_url: https://www.linkedin.com/company/illsa-international-language-and-linguistics-students-association/
pinterest_url:
slack_url:
twitter_url: https://twitter.com/ILLSAorg

# Build settings
markdown: kramdown
