# Site settings
title: ILLSA
subtitle: International Language and Linguistics Students' Association
email: presidency.illsa@gmail.com
description: A FREE AND FULLY RESPONSIVE SITE TEMPLATE
baseurl: "/" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
author:
street_address: 1234 Somewhere Road
city: Nashville
state: TN
zip_code: 55555
country: United States of America
phone: (716) 555-5555

# Social settings
500px_url:
facebook_url: https://www.facebook.com/illsaorg
github_url:
gitlab_url: 
googleplus_url: 
instagram_url: https://instagram.com
linkedin_url: https://www.linkedin.com/company/illsa-international-language-and-linguistics-students-association/
pinterest_url:
slack_url:
twitter_url: https://twitter.com/ILLSAorg

# Build settings
markdown: kramdown
