# Change 'comments' to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: 'millennial-3'

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-ID: 'UA-112060364-2'

menu:
- {name: 'Tagung', folder: 'pages', file: 'about.html'}
- {name: 'Archiv', folder: 'pages', file: 'archive.html'}
#- {name: 'Teilnehmen', folder: 'pages', file: 'partake.html'}
- {name: 'Ausrichten', folder: 'pages', file: 'host.html'}
- {name: 'Schwestern', folder: 'pages', file: 'sisters.html'}
- {name: 'Kontakt', folder: 'pages', file: 'contact.html'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
- {icon: 'twitter', link: 'https://twitter.com/StuTS_official'}
- {icon: 'facebook', link: 'https://www.facebook.com/jungesprachwissenschaft'}
- {icon: 'instagram', link: 'https://www.instagram.com/jungesprachwissenschaft/'}
- {icon: 'envelope', link: 'mailto:2020@linguistik.computer'}
- {icon: 'rss-square', link: 'feed.xml'}
# - {icon: 'rss-square', link: 'rss-feed.xml'}

# Customize site text
pagination:
  next_page: 'Nachf.'
  previous_page: 'Vorg.'

sharing_button_prompt: 'Feel free to share!'

related_posts: 'Verwandte Artikel'

post_date_prefix: ''
